image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start MySQL Server and Create Database
    command: |
      service mysql start
      echo "CREATE DATABASE crud; GRANT ALL PRIVILEGES ON crud.* TO 'root'@'localhost' IDENTIFIED BY 'root';" | mysql