version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: my-web-app
    ports:
      - "8000:80"
    volumes:
      - ./Crud-app:/var/www/html/
    working_dir: /var/www/html/
    command: >
      bash -c '
        service apache2 start &&
        sleep 5 &&
        service mysql start &&
        sleep 5 &&
        mysql -e "CREATE DATABASE crud;" &&
        mysql -e "CREATE USER '\''superadmin'\''@'\''localhost'\'' IDENTIFIED BY '\''password'\'';" &&
        mysql -e "GRANT ALL PRIVILEGES ON crud.* TO '\''superadmin'\''@'\''localhost'\'';" &&
        composer install &&
        php artisan serve --host=0.0.0.0 --port=80'

  db:
    image: mysql:5.7
    container_name: my-db
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: superadmin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
