image:
  file: .gitpod.Dockerfile
tasks:
  - name: Start MySQL Server and Create Database
    command: |
      service mysql start
      sleep 20
      mysql -e "CREATE DATABASE crud;"
      mysql -e "CREATE USER 'superadmin'@'localhost' IDENTIFIED BY 'password';"
      mysql -e "GRANT ALL PRIVILEGES ON crud.* TO 'superadmin'@'localhost';"
      cd Crud-app
      composer install
      php artisan serve
ports:
  - port: 8000
    onOpen: open-preview
