image:
  file: .gitpod.Dockerfile
ports:
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore
tasks:
  - name: Start MySQL Server and Create Database
    command: |
      service mysql start
      sleep 20
      mysql -e "CREATE DATABASE crud;"
      mysql -e "CREATE USER 'superadmin'@'localhost' IDENTIFIED BY 'password';"
      mysql -e "GRANT ALL PRIVILEGES ON crud.* TO 'superadmin'@'localhost';"
      cd Crud-app
      cp .env.example .env &&
      sed -i "s|DB_PASSWORD=|DB_PASSWORD=password|g" .env &&
      sed -i "s|DB_DATABASE=|DB_DATABASE=crud|g" .env &&
      sed -i "s|DB_USERNAME=|DB_USERNAME=superadmin|g" .env &&
      composer install &&
      php artisan key:generate &&
      php artisan migrate &&
      php artisan serve --port=8000



