image:
  file: .gitpod.Dockerfile
tasks:
  - name: Start MySQL Server and Create Database
    command: |
      service mysql start
      sleep 20
      mysql -e "CREATE DATABASE crud;"
       sleep 20
      mysql -e "CREATE DATABASE crud;"
      mysql -e "CREATE USER 'superadmin'@'localhost' IDENTIFIED BY 'password';"
      mysql -e "GRANT ALL PRIVILEGES ON crud.* TO 'superadmin'@'localhost';"
