image:
  file: .gitpod.Dockerfile
tasks:
  - name: Start MySQL Server and Create Database
    command: |
      service mysql start
      mysql -e "CREATE DATABASE crud;"
#      echo "CREATE USER 'superadmin'@'localhost' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'superadmin'@'localhost' WITH GRANT OPTION;" | mysql